// Personal Questions (Section 2 + Section 5 from question bank)
export const PERSONAL_QUESTIONS = [
  { question: "This is your third attempt at CEED. What changed in how you prepared this time, and what does that persistence say about why you want this specifically?", idealAnswer: "Be honest about what failed before — preparation gaps, not commitment gaps. Show growth: what specific skills or knowledge you built since. The persistence itself is evidence of conviction — name why design graduate school specifically, not just 'design'." },
  { question: "Why M.Des now — after over two years of professional experience? What gap does the degree fill that work experience cannot?", idealAnswer: "Work gives you execution skills; a masters gives you research depth, conceptual rigour, and the space to ask bigger questions. Name the specific gap — is it methods, theory, specialisation? Connect it to a research interest you couldn't pursue in professional settings." },
  { question: "Your first preference is SPD. The interview is common with XR. Make the case for why SPD and not XR, given that your portfolio work is entirely screen-based.", idealAnswer: "SPD sits at the intersection of physical form, digital interaction, and services — your screen work is a subset of that, not opposed to it. Show you understand what SPD adds: product lifecycle, material considerations, IoT, service ecosystems. Be honest that you'd engage with XR if admitted." },
  { question: "What has changed about your design thinking between your first CEED attempt and now?", idealAnswer: "Be specific — not 'I've grown.' Name a concept you misunderstood before and now grasp, a bias you've corrected, a type of problem you see differently. Show intellectual evolution, not just effort." },
  { question: "What designer or design thinker has most influenced how you work, and why?", idealAnswer: "Don't name the most famous person — name someone whose work specifically shaped a decision you've made. Explain the idea, how you encountered it, and where you applied it. Parroting names scores nothing; a genuine connection scores a lot." },
  { question: "Describe a project or decision where you were wrong. What did you learn from it?", idealAnswer: "Pick something real and design-relevant. Describe what you assumed, why you were wrong, what the evidence showed, and what you'd do differently. The quality of your reflection matters more than the severity of the mistake." },
  { question: "What do you want to research or design in your M.Des that your professional work hasn't allowed you to explore?", idealAnswer: "Name a specific area: speculative design, design for behaviour change, accessible technology, rural design contexts. Connect it to IIT Jodhpur faculty or lab work. Do not say 'I want to explore design broadly'." },
  { question: "Where do you see yourself five years after completing the M.Des?", idealAnswer: "Be honest but specific — academia, practice, entrepreneurship, policy. Tie it to what you want to research during the programme. Avoid 'I want to make an impact' — say what change you'd make and for whom." },
  { question: "Why IIT Jodhpur specifically — what about this programme's SPD curriculum or faculty drew you to it over other M.Des programmes?", idealAnswer: "Name specific faculty research areas, labs, or programme features. Show you've read beyond the website. Connect their focus to your interests. Do not say 'IIT brand' — say what uniquely exists here that doesn't elsewhere." },
  { question: "Your portfolio shows two very different problem spaces. Which type of problem do you find more interesting to design for, and why?", idealAnswer: "Don't hedge — pick one and argue for it. Show self-awareness about your strengths and what kind of design thinking energises you. Use a specific project moment to illustrate why." },
  // Section 5 — Background & Professional Experience
  { question: "You studied Industrial Design at NIT Rourkela. How has physical product thinking — ergonomics, materials, form — influenced how you approach UI/UX work?", idealAnswer: "Connect specific ID concepts to your digital work: affordance theory, ergonomic constraint, form-function alignment. Show one example where your ID training changed a digital decision. Don't claim it influenced everything — be precise." },
  { question: "You have freelance experience. What did working independently teach you that working at a company couldn't?", idealAnswer: "Name the specific skills: client communication, scoping work, making decisions without a team, owning the full process. Contrast with agency/company work honestly — neither is better, they teach different things." },
  { question: "At your company you worked on SaaS design. What is the biggest design challenge specific to SaaS products that doesn't exist in consumer apps?", idealAnswer: "Power users vs. new users, complex permission models, multi-tenant systems, onboarding for enterprise teams. Pick one and go deep with an example from your work." },
  { question: "Your B.Tech is in Industrial Design but most of your portfolio is digital. Do you consider yourself a product designer, a UX designer, or something else — and why does it matter?", idealAnswer: "The label matters less than what it signals about how you think. A product designer thinks in systems; a UX designer focuses on the user journey; an ID graduate thinks about form and physical context too. Own the intersection — it's your differentiator." },
  { question: "What is a design system and why does it matter? Have you built or contributed to one?", idealAnswer: "A design system is a shared language of components, tokens, and guidelines that keeps product teams consistent at scale. It matters because it removes redundant decisions and reduces inconsistency across teams. If you've contributed, describe what decisions you made and why." },
  { question: "How do you stay current with what's happening in design — what are you reading, watching, or following?", idealAnswer: "Name specific sources: NNGroup, Figma blog, IDEO publications, specific designers on social media, design books. Show you have taste, not just general curiosity. Mention something recent you read and what you took from it." },
  { question: "What is the difference between a design problem and a business problem? Can you give an example from your work?", idealAnswer: "A business problem is about revenue, retention, or efficiency. A design problem is about how people experience, understand, or use something. They overlap — the best design work solves both. Name a specific situation where you had to translate a business ask into a design brief." },
  { question: "What is the role of prototyping in your process — when do you prototype and at what fidelity?", idealAnswer: "Prototype to answer a specific question, not to show progress. Low fidelity to test concepts and flows; high fidelity to test visual hierarchy and micro-interactions. Name a project where fidelity choice mattered and why." },
];

// Case Study Questions (Section 1 — Portfolio Questions)
export const CASE_STUDY_QUESTIONS = [
  { question: "Walk us through your overall design process in your key project — from problem identification to final solution.", idealAnswer: "Structure: problem discovery → research → insight synthesis → ideation → prototyping → testing → iteration. Don't rush to the solution. Spend time on what you found in research and how it shaped your decisions." },
  { question: "Your concept prototype hasn't been tested with actual users from the target group. How do you defend the design decisions without that validation?", idealAnswer: "Acknowledge the gap directly — pretending it doesn't exist loses credibility. Then explain what proxies you used: analogous user research, expert reviews, heuristic evaluation, existing literature. Name what you'd test first if you had access." },
  { question: "Both your projects involve making complex systems accessible to non-expert users. Is that a conscious design interest or a coincidence?", idealAnswer: "If it's conscious, name the belief behind it — complexity is a design failure, not a user failure. If it's a pattern you noticed retrospectively, reflect on what that says about your instincts. Either answer is fine; the reflection is what matters." },
  { question: "What would you have designed differently if the primary user was different from who you originally designed for?", idealAnswer: "Identify which decisions were user-specific: language, mental models, trust signals, information density. Show you can flip your assumptions and redesign from a different starting point — this tests your flexibility." },
  { question: "You designed for a community you may not belong to. How did you manage that distance responsibly?", idealAnswer: "Name what you did: desk research, secondary sources, expert interviews, community contact. Acknowledge what you couldn't fully access. Name the specific design decisions where this distance created uncertainty and how you handled it." },
  { question: "A concept or approach failed in testing. What does that tell you about the relationship between the design principle you were testing and user reality?", idealAnswer: "Be specific about what failed and why — not 'users didn't like it' but what assumption broke. Connect it to a broader principle: creative freedom vs structure, familiarity vs novelty, etc." },
  { question: "If a key interaction modality (voice, touch, gesture) was unavailable for your design, how would your solution change?", idealAnswer: "Show you understand why you chose that modality: what user context made it appropriate. Then genuinely redesign — don't just swap modalities, rethink the core interaction model for the new constraint." },
  { question: "What would be your metrics for success if your main project were launched? What would you track in the first 3 months?", idealAnswer: "Separate leading indicators from lagging ones. Engagement metrics (task completion, return rate) tell you usability; outcome metrics (user-reported confidence, financial decisions made) tell you impact. Name 3–4 specific metrics and why each one." },
  { question: "What ethical responsibility did you feel while designing a product for a vulnerable user group? Did it constrain any design decision?", idealAnswer: "Name a specific decision where ethics created a real constraint — not a theoretical one. Show you can articulate the trade-off: e.g. 'I could have used X pattern for engagement, but it would have exploited anxiety rather than built confidence, so I chose Y instead.'" },
  { question: "How is designing for safety different from designing for usability?", idealAnswer: "Usability is about task efficiency; safety is about reducing risk of harm — which sometimes means adding friction. Give a specific example where the most usable design wasn't the safest, and how you resolved that tension." },
  { question: "If you had to critique your own portfolio — what is its biggest weakness?", idealAnswer: "Be honest: no real user testing? Narrow problem space? Limited technical implementation? The faculty will spot weaknesses anyway — your self-awareness shows design maturity. Follow the weakness with what you're actively doing about it." },
  { question: "What is the difference between problem validation and solution validation? How does this apply to your work?", idealAnswer: "Problem validation: confirming the problem exists and matters to real users. Solution validation: confirming your solution addresses it effectively. Many student projects validate the solution but not the problem. Name which you did well and which you skipped." },
  { question: "What does iteration mean in your process? Describe a specific change you made after testing.", idealAnswer: "Iteration is not decoration — it's changing a decision based on evidence. Name the specific version, what you tested, what you observed, what hypothesis that broke, and what you changed as a result." },
  { question: "Redesign the experience of standing in a queue at a government office in India.", idealAnswer: "Frame pain points: time uncertainty, no status visibility, power imbalance, dignity. Consider both digital and physical interventions. Avoid smartphone-only solutions — consider SMS, token systems, signage. Propose something testable and scoped, not utopian." },
];

// Technical Questions (Section 3 — SPD + Section 4 — XR)
export const TECHNICAL_QUESTIONS = [
  // SPD Domain
  { question: "What is Smart Product Design? How is it different from Industrial Design or UX Design?", idealAnswer: "SPD sits at the intersection of physical form, digital intelligence, and service ecosystems. ID focuses on form and manufacturing; UX focuses on screen interactions; SPD integrates all three plus connectivity, data, and product lifecycle. Give a product example that shows all three layers." },
  { question: "Give an example of a smart product you use daily. What makes its design successful or unsuccessful?", idealAnswer: "Pick one product and go deep. Evaluate: does the physical form communicate the digital function? Is the app-product relationship coherent? Does it fail gracefully? Show you can critique at multiple levels, not just aesthetics." },
  { question: "How does IoT change the designer's role — what new responsibilities does a connected product create that a non-connected product doesn't?", idealAnswer: "Data ethics, software update cycles, server dependency, cross-device coherence, privacy design. The designer is now responsible for the product's behaviour over time, not just at point of purchase. Give one specific example of a design responsibility that IoT introduced." },
  { question: "What is the difference between a product's interface and its interaction? Give an example where they diverge.", idealAnswer: "Interface is the control surface (screen, buttons, lights). Interaction is the conversation over time between user and product. A product can have a minimal interface but rich interaction (e.g. a smart speaker). Show you understand this distinction." },
  { question: "How would you approach designing a smart product for rural India — what constraints would fundamentally change your design process?", idealAnswer: "Constraints: low/no connectivity, power reliability, low digital literacy, shared device use, local language. These aren't edge cases — they're the design brief. Show that you'd start from context, not from a city-designed product and adapt." },
  { question: "What is service design, and how does it relate to smart product design? Give a real example.", idealAnswer: "Service design maps the full journey: touchpoints, backstage processes, and stakeholders. A smart product is often one touchpoint in a larger service. Example: a connected health device is part of a health service — clinic visit, app, insurance, support. Show you can think beyond the product." },
  { question: "A smart product collects user data to improve its experience. Where do you draw the ethical line between personalisation and surveillance?", idealAnswer: "The line is consent, transparency, and proportionality. Data used to improve your experience vs data sold or used to manipulate. Name a design decision that operationalises this — a privacy setting, a data minimisation choice, a transparency feature." },
  { question: "What role does physical form play in a smart product when most of its functionality is digital?", idealAnswer: "Form communicates trust, brand, and context of use. It signals how to hold, where to place, when it's active. Physical affordances guide first-time use without onboarding. Name a product where form and digital function are well-integrated vs poorly integrated." },
  { question: "Name a smart product you think is designed poorly. What specifically would you change about it?", idealAnswer: "Be specific — not 'smart TVs are bad' but 'the remote-app disconnect in smart TVs creates cognitive overhead because...' Propose a specific change and explain why it solves the problem. Show taste and analytical thinking together." },
  { question: "How do you think about designing for product lifecycle — what happens to a smart product when the company discontinues software support?", idealAnswer: "This is a real crisis in IoT: products becoming useless or insecure post-support. Design responses: open standards, local-only fallback modes, repair-focused hardware design, right-to-repair. Show you see design responsibility beyond launch." },
  { question: "What is human-centred design and what are its limitations? When is it not the right approach?", idealAnswer: "HCD limitations: it can optimise for individual user satisfaction at the expense of collective or environmental impact. It can entrench existing mental models rather than challenge them. It can be co-opted as a veneer of empathy without structural change. Give a concrete example of where HCD fell short." },
  { question: "If you had to design a smart product that helps elderly users in India manage medication, where would you start?", idealAnswer: "Start with context: who manages medication — patient, caregiver, or both? What fails today — memory, understanding, access? Interview both users. Consider literacy, vision, dexterity. Avoid assuming a smartphone app. Think about alarm systems, physical pill organisers with digital tracking, family notification loops." },
  { question: "How do you think about the relationship between technology and design? Does technology constrain design or enable it?", idealAnswer: "Both — technology creates new possibility spaces and closes others. The designer's job is to understand the material (technology) deeply enough to know what's genuinely possible and what's a feature looking for a problem. Give one example of technology enabling a design you couldn't have done otherwise, and one where it constrained you." },
  // XR Domain
  { question: "What is XR and what are its three sub-categories? How do they differ in terms of user experience?", idealAnswer: "XR = extended reality umbrella. AR: overlays digital content on physical world (user stays present in environment). VR: fully immersive synthetic environment (user is displaced). MR: digital and physical objects interact in real time (higher fidelity than AR). Key UX difference: level of presence and degree to which physical context matters." },
  { question: "What is presence in VR design, and what breaks it? Give a specific example.", idealAnswer: "Presence is the subjective feeling of being in the virtual environment. Breaks: motion sickness from latency mismatches, visual inconsistencies, controller tracking loss, social isolation reminders. Example: a VR training simulation where a low-poly hand model breaks presence because it doesn't match expected proprioception." },
  { question: "How does spatial interaction design differ from screen-based interaction design — what new design skills does it require?", idealAnswer: "No persistent cursor, no keyboard shortcuts, 3D space without gravity defaults, gaze and gesture as input. New skills: depth affordance design, spatial audio cues, embodied interaction, locomotion design, occlusion management. Show you understand these aren't just screen concepts rotated 90 degrees." },
  { question: "What is the most significant unsolved UX problem in XR today?", idealAnswer: "Candidates: input fatigue (arm tracking is physically tiring), social acceptance (wearing a headset in public), onboarding complexity, text input, accessibility for users with motor or visual impairments. Pick one, go deep, and show awareness of current attempts to solve it." },
  { question: "If you were designing an AR application for a construction site, what would your user research process look like?", idealAnswer: "Contextual inquiry on-site: observe work patterns, lighting conditions, noise levels, glove use, safety protocols. Identify tasks where AR adds value vs creates hazard. Consider: hands-free interaction, sunlight glare on displays, dust and physical robustness. Don't design from a clean desk." },
  { question: "Your portfolio has no XR work. If you were admitted to the XR track, how would you bridge that gap?", idealAnswer: "Be honest — don't pretend this isn't a real gap. Name what you'd do immediately: self-directed XR projects, WebXR prototyping, engaging with XR literature. Show that your screen-based interaction skills transfer: information architecture, interaction patterns, accessibility thinking all apply. Name one XR problem you're genuinely curious about." },
  { question: "What is the difference between diegetic and non-diegetic UI in XR? Give a design example of each.", idealAnswer: "Diegetic UI exists within the world of the experience — a watch on a character's wrist, a screen on a wall. Non-diegetic UI floats outside the world — health bars, subtitles. In XR design: diegetic UI increases presence; non-diegetic UI breaks it but is sometimes necessary for critical information." },
  { question: "How do you think about accessibility in XR — what user groups are currently most excluded from XR experiences?", idealAnswer: "Users with vestibular disorders (motion sickness risk), motor disabilities (gesture/controller dependency), visual impairments, deaf users (spatial audio reliance), and users who cannot wear headsets for physical or sensory reasons. Name specific design responses: seated-mode options, eye-gaze input, haptic feedback for audio cues." },
];
